### ISSUE TITLE
ThemeService that doesn't rely on DI

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#1088]
## What would you like to be added:

An extension method (on Window) that can be used to generate an IThemeService from a window instance
eg 
IThemeService theme = window.GetThemeService();

The GetThemeService method would optionally take an ILogger

## Why is this needed:

Not everyone will want to use uno.extensions DI framework

## Anything else we need to know?
The current ThemeService implementation requires
```
		ILogger<ThemeService> logger,
		Window window,
		IDispatcher dispatcher,
		IWritableOptions<ThemeSettings> writeSettings)
```
The GetThemeService method would need to retrieve an IDispatcher instance. 
The ILogger parameter would be optional.
Since there's no DI and/or configuration, the ThemeService implementation would be changed to use application settings, rather than writableoptions.

**Comment by dansiegel** [comment]
In reviewing the implementation of the ThemeService the Window should not be among the parameters because it is not what is needed. It should instead be the XamlRoot itself. I would suggest any extension method be on both the Window and UIElement this would for instance make it easier to instantiate the ThemeService from the context of a Page or other Control.
