### ISSUE TITLE
OIDC Authority issue

### ISSUE THREAD

**Issue by quintonv** [unoplatform/uno.extensions#1574]
### Current behavior

I am trying out the latest UNO template and chose the OIDC auth in the wizzard. I double checked that appsettings has the settings for the hosted identity server.
When I start the mobile application in Android I just get a error on start. "No Authority Specified", I definitely have it in appsettings and in the dev version of it too.

### Expected behavior

App should start up

### How to reproduce it (as minimally and precisely as possible)

Create a new project using the Uno Platform Template

### Workaround

none

### Works on UWP/WinUI

None

### Affected platforms

Solution Templates

### IDE

Visual Studio 2022

**Comment by nickrandolph** [comment]
Hi @quintonv loading from appsettings should work but to validate that there's not something else going wrong, can you try setting these values in code (`[see this example](https://github.com/unoplatform/uno.extensions/blob/1a9beaad5b02f382e8d656cd5b6ffc39278a8d8a/testing/TestHarness/TestHarness.Shared/Ext/Authentication/Oidc/OidcAuthenticationHostInit.cs#L14)`)

**Comment by xperiandri** [comment]
@nickrandolph we reproduced the issue with @dim-37
Especially if we add 2 providers, then options load from the last in the `appsettings.json`
Is there a tutorial how to run tests here?
We can clone, create repro and fix if we know what is the process.

**Comment by nickrandolph** [comment]
The tests for auth are all manual at the moment. You should be able to run the TestHarness app and check out the authentication pages.
With multiple providers you may need to name them so they load correctly.

**Comment by nickrandolph** [comment]
@xperiandri do you have a simple repro for this that you can upload. We'll action asap and get a fix pushed

**Comment by xperiandri** [comment]
@nickrandolph we prepared a fix

**Comment by nickrandolph** [comment]
I'm not sure I understand what the actual problem is here (please provide a repro sample) nor what the proposed solution is trying to do.
Support for mulitple OIDC providers is done by using named config sections and calling the AddOidc multiple times.

**Comment by xperiandri** [comment]
Because the options are null binding them from configuration does nothing.
@dim-37 modify the test app to have 2 providers in JSON to test that in this repo

**Comment by dim-37** [comment]
Here is a test repository with the reproduced error 
https://github.com/dim-37/TestMultipleOIDC/tree/master
In it I create 2 OIDC providers one with completely empty parameters the other with working values from TestHarness app then I try to log in with the provider with empty values and instead of getting an error due to empty values it uses the values of the last registered provider in this case the provider with values from the TestHarness app.

**Comment by nickrandolph** [comment]
Ok so thanks for submitting this issue, along with the repo. I've tracked down what the cause of this is and have pushed a draft PR : https://github.com/unoplatform/uno.extensions/pull/1889
Once this has built the packages, if you can verify that it fixes your issue that would be great.
There's a bit more work to be done on this to make sure that the fix is applied correctly to all the auth providers

**Comment by nickrandolph** [comment]
I've applied the changes I did for OIDC to both MSAL and Web auth providers for consistency. Custom auth doesn't currently support reading from settings, so did not require this fix
