### ISSUE TITLE
[Android][Commerce App] Cart page items are not scrollable

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#204]
**IMPORTANT: Please double-check the other platforms while working on this issue and also both UWP/WinUI folders**

## Current behavior

Cart page items are not scrollable
Note: you can actually scroll, but just not on the items themselves, presumably the SwipeItem are blocking the scrolling gesture

## Expected behavior

Cart page items are scrollable

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Navigate to the Cart tab
- Try to scroll the list of the items in the page

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [ ] iOS
- [ ] macOS
- [X] Android
- [ ] WebAssembly
- [ ] Skia
- [ ] Windows
- [ ] Build tasks

**Comment by nickrandolph** [comment]
@agneszitte-nventive wouldn't the cart work better if the Checkout button was permanently at the bottom of the screen and the list was allowed to scroll in the center of the page? The way the whole content scrolls at the moment feels a bit wonky.
I'm asking because we may be trying to solve the wrong problem (ie getting the whole page to scroll)
