### ISSUE TITLE
[Navigation] Out of order routemaps with dependson don't work

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#2149]
## Current behavior

The following related RouteMap won't work - attempting to navigate to PageNavigationTwo will result in only PageNavigationTwo being navigated to, with nothing on the frame backstack
```
new RouteMap("PageNavigationTwo", View: views.FindByViewModel<PageNavigationTwoViewModel>(), IsDefault: true, DependsOn: "PageNavigationOne"),
new RouteMap("PageNavigationOne", View: views.FindByViewModel<PageNavigationOneViewModel>()),

```
## Expected behavior

In the provided example, navigation should go to PageNavigationTwo but PageNavigationOne should be inserted in the back stack

## Environment

Nuget Package (s):

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [ ] 2022 (version: )
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MarkAllan007** [comment]
Is the expected behavior "In the provided example, navigation should go to PageNavigationTwo but PageNavigationOne should be inserted in the back stack" accurate?

I did not know that the string assignments "RouteMap("PageNavigationTwo", View: views.FindByViewModel<PageNavigationTwoViewModel>()" drove the priority of when pages can or are displayed.

This could make the route-mapping overly complex, yes? Especially when working with MVUX?

Would it not be better to specify a ViewMap root page, then let an apps' business logic requirements manage the priority or sequence of when pages are displayed? 

I have not been looking at this, I am not familiar with the goals of the system of application. I don't want to distract anyone from their work.

Thanks,
Mark Allan
