### ISSUE TITLE
[Configuration] ImmutableList parameter can't be modified in IWritableOptions's UpdateAsync  

### ISSUE THREAD

**Issue by thierry-fortin1** [unoplatform/uno.extensions#659]
## Context
I have a IWritableOptions<HosOptions>: 
![image](https://user-images.githubusercontent.com/105242267/184912536-f90e22a3-8a36-4de6-92bc-d6a98c5e3ab2.png)
And HosOptions is that: 
![image](https://user-images.githubusercontent.com/105242267/184912721-05da9fef-ae82-4b1b-912c-67b9151495d0.png)
I don't have any problems with IWritableOptions when the parameters aren't lists.

## Current behavior
I want to update _hosConfig.Value.HiddenZones (add or remove a item in the ImmutableList, depending on if HiddenZones already has the zone in its list).

ImmutableList<OperatingZone> (doesn't work)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/105242267/184912343-fa75cb16-b52f-44ae-be95-35448aa0bd14.png)
![image](https://user-images.githubusercontent.com/105242267/184905642-909cbf92-d08f-4da9-b604-be64607d8412.png)

List<OperatingZone> (works)
![image](https://user-images.githubusercontent.com/105242267/184917392-3c281fb7-c47e-4799-bb46-2cc980b3fe11.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/105242267/184911906-a0db3bdb-1ba4-487b-ad4f-21e0ffe9a941.png)
![image](https://user-images.githubusercontent.com/105242267/184916570-aaabc2a2-a5dc-44ff-85a1-8f720a121cb7.png)

## Expected behavior
Updating a ImmutableList should work in UpdateAsync, in this example, HiddenZones should be modified.

## Environment

Nuget Package:
2.2.0-dev.79

Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [X] 2022 (version: 17.3.0)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by thierry-fortin1** [comment]
@dr1rrb

**Comment by dr1rrb** [comment]
@nickrandolph Looking at the code, I found that when we are updating the value using the `UpdateAsync(Func<T, T>)` we are not updating the sync value `Value` https://github.com/unoplatform/uno.extensions/blob/94f3cb314adb385c25d9bab153d0adab89793d13/src/Uno.Extensions.Configuration/WritableOptions.cs#L65 I would imagine that is the root cause of the issue as we are using it for subsequent write operations (which is also a concern if we have concurrent updates).

BTW I would actually remove the `UpdateAsync(Action<T>)` from the `IWriteableOption<T>` interface. Since we are encouraging the use of immutability, this is error prompt (and we can then improve perf by assuming that if we do have the same instance, from the `ppalycChanges`, we can just abort the update)

**Comment by nickrandolph** [comment]
I agree that we should remove UpdateAsync(Action<T>) as it can lead to some confusion and that immutability would be the preference.
This said, there's a bug in the above code in that it assume that hos.HiddenZones is being updated? It's an ImmutableList, which means that any action (ie Add/Remove) will return a new ImmutableList. The code should look like
`hos = hos with { HiddenList = hos.HiddenList.Add(zone) };
`
I will need to double check but I don't think we need to update the value object, since it's an IOptionsMonitor. so the underlying value will be updated when we reload configuration. That said, we possibly need to look at making this thread safe to ensure no reads/writes happen when a write is taking place.

**Comment by dr1rrb** [comment]
> This said, there's a bug in the above code in that it assume that hos.HiddenZones is being updated? It's an ImmutableList, which means that any action (ie Add/Remove) will return a new ImmutableList. The code should look like `hos = hos with { HiddenList = hos.HiddenList.Add(zone) }; ` 

That's exactly what was done when using immutable list, the version you are looking at is the "workaround".

BTW @thierry-fortin1 looking at your screenshot of the "quick watch", it's expected that the `hos.HiddenZones` remains to 0 at the end of the delegate : we are **NOT** modifying the `hos`, we are creating a new instance. What you want to evaluate is the whole line `hos with { HiddenZones = hidden }` (depending of the debugger you are using, you can try to add a watch for `$return`)

**Comment by nickrandolph** [comment]
It's likely that there's an issue with the serialization of the immutablelist - it must be failing to be written to the .json file, meaning that when the configuration is reloaded it's not being populated into the value

**Comment by thierry-fortin1** [comment]
> BTW @thierry-fortin1 looking at your screenshot of the "quick watch", it's expected that the hos.HiddenZones remains to 0 at the end of the delegate : we are NOT modifying the hos, we are creating a new instance. What you want to evaluate is the whole line hos with { HiddenZones = hidden } (depending of the debugger you are using, you can try to add a watch for $return)

I checked after the UpdateAsync finished in the local variables, and _hosConfig still has no values in HiddenZones.
![image](https://user-images.githubusercontent.com/105242267/185153019-dff5bf5c-310b-4b55-8ee2-fa89c4bf0831.png)
And I called the function a second time for another zone in the UI, then _hosConfig.Value.HiddenZones should at that moment have one value, but it didn't and it was still empty.

**Comment by nickrandolph** [comment]
@thierry-fortin1 you should be able to update to the latest uno.extensions dev package which now has support for Immutablelist for reading/writing configuration and settings.
